### ISSUE TITLE
Add pre-push hook.

### ISSUE THREAD

**Issue by alexcouper** [alexcouper/captainhook#35]
I want to play "push it" by salt n pepa on _every_ push.

**Comment by jeremykenedy** [comment]
Hi,

You can use quicktime to snip your mp3 and the native mac command line player to play it from command line.

Please see below.

    


    #!/bin/bash
    
    ## ADD VARIABLES HERE ##
    _yourSoundFileAndPath="/Users/jeremykenedy/Desktop/pushit-jk-master/pushit8s.m4a"
    
    ## ADD ALIAS'S HERE ##
    alias pushitmaster="git push origin master;afplay "$_yourSoundFileAndPath

I also created a repo @ https://github.com/jeremykenedy/pushit

Yay !

Jeremy :)

**Comment by alexcouper** [comment]
Nice @jeremykenedy - I'll see if afplay suffers from the same behaviour as mplayer when combined with a git hook.

**Comment by alexcouper** [comment]
yeah unfortunately it looks like alias-ing is the only way to get this to work on mac.

Somehow (I have no idea how) the git push waits for the script to play despite the process being forked.

![git-funnies](https://cloud.githubusercontent.com/assets/837734/8330867/131f5256-1a74-11e5-91e1-3e3c02aff5d2.gif)
