### ISSUE TITLE
isort check fails for valid files with isort >=4.1.0 

### ISSUE THREAD

**Issue by mknecht** [alexcouper/captainhook#94]
`isort` considers the file valid, but the check fails because no output is expected — but isort now always displays a logo in the command-line.

The [changelog entry](https://github.com/timothycrosley/isort/blob/develop/CHANGELOG.md):

    Added the isort logo to the command line interface

Example run of captainhook without errors, but still rejecting the commit:

    $ captainhook run
    ===============================================================================
    Checking isort
    ===============================================================================
    /#######################################################################\
    
         `sMMy`
         .yyyy-                                                      `
        ##soos##                                                    ./o.
              `     ``..-..`         ``...`.``         `   ```` ``-ssso```
         .s:-y-   .+osssssso/.     ./ossss+:so+:`    :+o-`/osso:+sssssssso/
         .s::y-   osss+.``.``     -ssss+-.`-ossso`   ssssso/::..::+ssss:::.
         .s::y-   /ssss+//:-.`   `ssss+     `ssss+   sssso`       :ssss`
         .s::y-   `-/+oossssso/  `ssss/      sssso   ssss/        :ssss`
         .y-/y-       ````:ssss`  ossso.    :ssss:   ssss/        :ssss.
         `/so:`    `-//::/osss+   `+ssss+-/ossso:    /sso-        `osssso/.
           \/      `-/oooo++/-      .:/++:/++/-`      ..           `://++/.
    
    
             isort your Python imports for you so you don't have to
    
                                VERSION 4.1.2
    
    \########################################################################/
    
    ===============================================================================
    Rejecting commit
    ===============================================================================

Two solutions: 
* Add `-q` when calling `isort`. Requires `isort` >=4.1.1, as the `quiet` option was introduced to remove the logo again. ^^
* Require isort <4.1

I'd favor the first, tested it locally, and would open a PR, if needed.

**Comment by alexcouper** [comment]
Option 1 is fine I think, we define the dependency in setup.py, so fixing that to anything above 4.1.1 is fine for me.
